### ISSUE TITLE
Can't open on Windows 11 64bits

### ISSUE THREAD

**Issue by mamarguerat** [peytoncasper/remarkable-sidekick#1]
After running the exe file an error occured as shown in the screenshot. The app seems to be installed. I have the icon on my desktop and in recently added apps.
![image](https://user-images.githubusercontent.com/49449909/153881568-afe5ddf3-b805-4ec7-b4b0-040a4bfe4e21.png)

**Comment by peytoncasper** [comment]
I appreciate you opening an issue for this, I'm currently looking into this and hoping to get a new version out soon. Looks like an issue with the cross compiled sharp library that I use on my M1 Mac. I'm looking into some options of using a Docker container to run electron-builder and generate a Windows/Linux version that work. 

At any rate, this will be fixed soon. :)

**Comment by peytoncasper** [comment]
I just released a 1.0.2 version, that I tested on a Windows VM but it was Windows 10. Let me know if this resolves the issue for you.

https://github.com/peytoncasper/remarkable-sidekick/releases

**Comment by mamarguerat** [comment]
It resolves the issue, thanks!
