### ISSUE TITLE
Can't open on Intel Mac, even in the newest 1.0.1 version

### ISSUE THREAD

**Issue by SkullCutter02** [peytoncasper/remarkable-sidekick#2]
Downloaded the mac img (the one with no arm). The following error shows up:

Seems like there's still a problem with the sharp library. 

<img width="415" alt="Screenshot 2022-02-15 at 12 40 06 PM" src="https://user-images.githubusercontent.com/64243477/153993767-f2c3fe63-3162-49f6-9d88-270b4b6a275a.png">

**Comment by peytoncasper** [comment]
Hi,

I appreciate you adding an issue for this. Let me know if this latest release works, I tested it on my M1 and on a Windows VM. I believe the fix should also resolve the issues on Intel Mac.

https://github.com/peytoncasper/remarkable-sidekick/releases

Thanks,
Peyton Casper

**Comment by SkullCutter02** [comment]
Hi it's fixed. Thanks!
