### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by adityasaky** [peytoncasper/remarkable-sidekick#3]
Hi! I want to package this for the Arch User Repositories (AUR) and I was wondering if you'd settled on a license for the app.

**Comment by peytoncasper** [comment]
I'll look into a few options tomorrow when I have some free time :). I'm really only familiar with MIT, so it'll likely be along those lines. At any rate, I'll get back to you shortly.

**Comment by adityasaky** [comment]
Cool, thanks!

**Comment by peytoncasper** [comment]
Just added a simple MIT License.
